/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package opennlp.tools.formats;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Locale;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import opennlp.tools.formats.MorfologikDictionaryReader.BaseFormEncoding;
import opennlp.tools.lemmatizer.DictionaryLemmatizer;

/**
 * Validates {@link MorfologikDictionaryReader}. The base-form decode cases and the end-to-end
 * dictionaries below were generated by morfologik's own encoder and serializer, so the reader is
 * checked against that library's output rather than against restated assumptions.
 */
public class MorfologikDictionaryReaderTest {

  // A CFSA2 dictionary of cat+A+NN, cats+B+NNS, dogs+B+NNS, mice+Douse+NN (SUFFIX encoder, '+'
  // separator, ISO-8859-1), built by morfologik's CFSA2Serializer.
  private static final String DICTIONARY_BASE64 =
      "XGZzYcYABxIAdXRtaWdkYVNEQkFvZWNzTitAXgMOHwYVw8TOzdHJzMHPzdHQcADMxc/RytHQ0GgAx8KRTxhLEQ==";

  // The same dictionary serialized in the older FSA5 format, to prove both formats are read.
  private static final String FSA5_DICTIONARY_BASE64 =
      "XGZzYQVfKwIAAABeBmPIAWQwAW0GaQZjBmUGKwZEBm8GdQZzBmUGKwZOBk4DAG8G"
          + "ZwZzBisGQgYrBk4GTgZTAwBhBnQGKxgCc2IBQfoA";

  private static final byte SEPARATOR = (byte) '+';

  /** Turkish folds {@code 'I'} to the dotless {@code 'ı'} (U+0131) instead of {@code 'i'}. */
  private static final Locale TURKISH = Locale.of("tr", "TR");

  private static byte[] iso(String s) {
    return s.getBytes(StandardCharsets.ISO_8859_1);
  }

  private static InputStream cfsa2() {
    return new ByteArrayInputStream(Base64.getDecoder().decode(DICTIONARY_BASE64));
  }

  private static InputStream info(String properties) {
    return new ByteArrayInputStream(iso(properties));
  }

  /** Each encoder recovers the base form morfologik encoded. */
  @ParameterizedTest
  @CsvSource({
      "SUFFIX, cats,    B,      cat",
      "SUFFIX, mice,    Douse,  mouse",
      "SUFFIX, foobar,  Gbar,   bar",
      "SUFFIX, cat,     A,      cat",
      "PREFIX, cats,    AB,     cat",
      "PREFIX, foobar,  DA,     bar",
      "PREFIX, unhappy, CA,     happy",
      "PREFIX, mice,    ADouse, mouse",
      "INFIX,  cats,    AAB,    cat",
      "INFIX,  foobar,  ADA,    bar",
      "INFIX,  unhappy, ACA,    happy",
      "INFIX,  mice,    AADouse, mouse",
      "NONE,   cats,    cat,    cat",
  })
  void testDecodeBaseForm(String encoder, String form, String encoded, String base) {
    final byte[] decoded = MorfologikDictionaryReader.decodeBaseForm(
        iso(form), iso(encoded), BaseFormEncoding.valueOf(encoder));
    Assertions.assertEquals(base, new String(decoded, StandardCharsets.ISO_8859_1));
  }

  /**
   * An encoded base form that is truncated, or whose control bytes address bytes the surface form
   * does not have, is rejected rather than silently decoded to nonsense.
   */
  @ParameterizedTest
  @CsvSource({
      // Fewer control bytes than the encoder needs.
      "SUFFIX, cat, ''",
      "PREFIX, cat, A",
      "INFIX,  cat, AA",
      // Control bytes addressing positions outside a three byte form.
      "SUFFIX, cat, Z",
      "PREFIX, cat, ZA",
      "INFIX,  cat, ZAA",
  })
  void testDecodeBaseFormRejectsMalformedEncoding(String encoder, String form, String encoded) {
    Assertions.assertThrows(IllegalArgumentException.class,
        () -> MorfologikDictionaryReader.decodeBaseForm(
            iso(form), iso(encoded), BaseFormEncoding.valueOf(encoder)));
  }

  private static DictionaryLemmatizer dictionary() throws IOException {
    return MorfologikDictionaryReader.read(
        cfsa2(), SEPARATOR, BaseFormEncoding.SUFFIX, StandardCharsets.ISO_8859_1);
  }

  /** The CFSA2 dictionary lemmatizes each surface form under its tag; misses yield "O". */
  @Test
  void testReadsCfsa2DictionaryEndToEnd() throws IOException {
    final DictionaryLemmatizer lemmatizer = dictionary();

    Assertions.assertArrayEquals(new String[] {"cat"},
        lemmatizer.lemmatize(new String[] {"cats"}, new String[] {"NNS"}));
    Assertions.assertArrayEquals(new String[] {"dog"},
        lemmatizer.lemmatize(new String[] {"dogs"}, new String[] {"NNS"}));
    Assertions.assertArrayEquals(new String[] {"mouse"},
        lemmatizer.lemmatize(new String[] {"mice"}, new String[] {"NN"}));
    Assertions.assertArrayEquals(new String[] {"cat"},
        lemmatizer.lemmatize(new String[] {"cat"}, new String[] {"NN"}));
    Assertions.assertArrayEquals(new String[] {"O"},
        lemmatizer.lemmatize(new String[] {"mice"}, new String[] {"NNS"}));
  }

  /**
   * Builds an FSA5 automaton accepting one ISO-8859-1 sequence.
   *
   * @param sequence The single sequence to accept, taken as ISO-8859-1 bytes.
   * @return The automaton, referenced by an open {@link InputStream}.
   */
  private InputStream fsa5WithSingleSequence(String sequence) {
    return new ByteArrayInputStream(FsaTestData.singleSequence(iso(sequence)));
  }

  /**
   * Surface forms have to fold the same way on every JVM. Under a Turkish default locale,
   * {@link String#toLowerCase()} folds {@code 'I'} to the dotless {@code 'ı'}, storing a key
   * that a lookup for {@code "istanbul"} can never reach, and the lemma silently degrades to
   * the {@code "O"} sentinel.
   */
  @Test
  void testFoldsFormsIndependentlyOfDefaultLocale() throws IOException {
    final Locale defaultLocale = Locale.getDefault();
    Locale.setDefault(TURKISH);
    try {
      final DictionaryLemmatizer lemmatizer = MorfologikDictionaryReader.read(
          fsa5WithSingleSequence("Istanbul+A+NNP"),
          SEPARATOR, BaseFormEncoding.SUFFIX, StandardCharsets.ISO_8859_1);

      Assertions.assertArrayEquals(new String[] {"Istanbul"},
          lemmatizer.lemmatize(new String[] {"istanbul"}, new String[] {"NNP"}));
    } finally {
      Locale.setDefault(defaultLocale);
    }
  }

  /** The same dictionary in the older FSA5 format is read identically. */
  @Test
  void testReadsFsa5DictionaryEndToEnd() throws IOException {
    final DictionaryLemmatizer lemmatizer = MorfologikDictionaryReader.read(
        new ByteArrayInputStream(Base64.getDecoder().decode(FSA5_DICTIONARY_BASE64)),
        SEPARATOR, BaseFormEncoding.SUFFIX, StandardCharsets.ISO_8859_1);

    Assertions.assertArrayEquals(new String[] {"mouse"},
        lemmatizer.lemmatize(new String[] {"mice"}, new String[] {"NN"}));
    Assertions.assertArrayEquals(new String[] {"cat"},
        lemmatizer.lemmatize(new String[] {"cats"}, new String[] {"NNS"}));
  }

  /** The separator, encoding, and encoder are taken from .info metadata when supplied. */
  @Test
  void testReadsWithInfoMetadata() throws IOException {
    final DictionaryLemmatizer lemmatizer = MorfologikDictionaryReader.read(cfsa2(),
        info("fsa.dict.separator=+\nfsa.dict.encoding=iso-8859-1\nfsa.dict.encoder=suffix\n"));

    Assertions.assertArrayEquals(new String[] {"mouse"},
        lemmatizer.lemmatize(new String[] {"mice"}, new String[] {"NN"}));
  }

  /** The encoder name in the metadata is matched without regard to case. */
  @Test
  void testEncoderNameIsCaseInsensitive() throws IOException {
    final DictionaryLemmatizer lemmatizer = MorfologikDictionaryReader.read(cfsa2(),
        info("fsa.dict.separator=+\nfsa.dict.encoding=iso-8859-1\nfsa.dict.encoder=Suffix\n"));

    Assertions.assertArrayEquals(new String[] {"mouse"},
        lemmatizer.lemmatize(new String[] {"mice"}, new String[] {"NN"}));
  }

  /** Missing required metadata fails loudly. */
  @Test
  void testMissingMetadataKeyRejected() {
    Assertions.assertThrows(IllegalArgumentException.class, () ->
        MorfologikDictionaryReader.read(cfsa2(), info("fsa.dict.separator=+\n")));
  }

  /** A separator that is not exactly one character fails loudly. */
  @Test
  void testMultiCharacterSeparatorRejected() {
    Assertions.assertThrows(IllegalArgumentException.class,
        () -> MorfologikDictionaryReader.read(cfsa2(),
            info("fsa.dict.separator=++\nfsa.dict.encoding=iso-8859-1\nfsa.dict.encoder=suffix\n")));
  }

  /** An encoder name no {@link BaseFormEncoding} constant matches fails loudly. */
  @Test
  void testUnknownEncoderRejected() {
    Assertions.assertThrows(IllegalArgumentException.class,
        () -> MorfologikDictionaryReader.read(cfsa2(),
            info("fsa.dict.separator=+\nfsa.dict.encoding=iso-8859-1\nfsa.dict.encoder=circumfix\n")));
  }

  /** An entry that carries no separator is reported instead of being read as a lemma-less form. */
  @Test
  void testEntryWithoutSeparatorRejected() {
    final IOException e = Assertions.assertThrows(IOException.class,
        () -> MorfologikDictionaryReader.read(
            cfsa2(), (byte) '~', BaseFormEncoding.SUFFIX, StandardCharsets.ISO_8859_1));
    Assertions.assertTrue(e.getMessage().startsWith("morfologik entry has no separator"),
        e.getMessage());
  }

  /** Null arguments are rejected at the boundary. */
  @Test
  void testNullArgumentsRejected() {
    Assertions.assertThrows(IllegalArgumentException.class, () -> MorfologikDictionaryReader.read(
        null, SEPARATOR, BaseFormEncoding.SUFFIX, StandardCharsets.ISO_8859_1));
    Assertions.assertThrows(IllegalArgumentException.class, () -> MorfologikDictionaryReader.read(
        cfsa2(), SEPARATOR, null, StandardCharsets.ISO_8859_1));
    Assertions.assertThrows(IllegalArgumentException.class, () -> MorfologikDictionaryReader.read(
        cfsa2(), SEPARATOR, BaseFormEncoding.SUFFIX, null));
    Assertions.assertThrows(IllegalArgumentException.class,
        () -> MorfologikDictionaryReader.read(null, info("fsa.dict.separator=+\n")));
    Assertions.assertThrows(IllegalArgumentException.class,
        () -> MorfologikDictionaryReader.read(cfsa2(), null));
  }
}
